/**
 * Generates supabase/seed.sql from the TypeScript seed content in src/content.
 * Run: npm run db:seed:generate
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { serviceSeeds } from "../src/content/services";
import { pageSeeds } from "../src/content/pages";
import { notificationSeed, settingsSeed } from "../src/content/settings";

const lit = (value: string | null | undefined) =>
  value === null || value === undefined ? "null" : `'${value.replace(/'/g, "''")}'`;
const textArray = (values: string[]) =>
  values.length === 0 ? "'{}'::text[]" : `array[${values.map(lit).join(", ")}]::text[]`;
const json = (value: unknown) => `${lit(JSON.stringify(value))}::jsonb`;

const lines: string[] = [
  "-- Generated by scripts/generate-seed.ts — do not edit by hand.",
  "-- Seeds default pages, services and settings. Safe to re-run: existing rows are left untouched.",
  "",
];

for (const [key, page] of Object.entries(pageSeeds)) {
  lines.push(
    `insert into public.pages (key, title, status, published_content, published_at) values (${lit(key)}, ${lit(
      page.title,
    )}, 'published', ${json(page.content)}, now()) on conflict (key) do nothing;`,
  );
}
lines.push("");

for (const s of serviceSeeds) {
  lines.push(
    `insert into public.services (slug, title, short_description, full_description, icon, problems, features, benefits, approach, technologies, faq, seo_title, seo_description, sort_order, status) values (${[
      lit(s.slug),
      lit(s.title),
      lit(s.shortDescription),
      lit(s.fullDescription),
      lit(s.icon),
      textArray(s.problems),
      json(s.features),
      textArray(s.benefits),
      json(s.approach),
      textArray(s.technologies),
      json(s.faq),
      lit(s.seoTitle),
      lit(s.seoDescription),
      String(s.sortOrder),
      "'published'",
    ].join(", ")}) on conflict (slug) do nothing;`,
  );
}
lines.push("");

for (const [key, value] of Object.entries(settingsSeed)) {
  lines.push(`insert into public.site_settings (key, value) values (${lit(key)}, ${json(value)}) on conflict (key) do nothing;`);
}
lines.push(
  `insert into public.site_settings (key, value) values ('notifications', ${json(notificationSeed)}) on conflict (key) do nothing;`,
);
lines.push("");

const out = resolve(process.cwd(), "supabase/seed.sql");
writeFileSync(out, lines.join("\n"));
console.log(`Wrote ${out}`);
